spring.application.name=S13-backend

spring.datasource.url=jdbc:mysql://localhost:3306/skill13
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080